openapi: 3.0.0
info:
    title: Simple API
    version: '1.0'

paths:
    /hello:
        get:
            summary: Returns a Greeting message
            responses:
                '200':
                    description: OK
                    Location:
                        Melbourne:
                            schema:
                                type: object
                                properties:
                                    message:
                                        type: string
                                example:
                                    message: 'Abhisheks web server'
